kind: pipeline
type: docker
name: default

clone:
  depth: 50
  tags: true
  skip_verify: true

steps:
- name: submodules
  image: alpine/git
  commands:
    - git submodule update --init --recursive
- name: build
  image: plugins/hugo
  volumes:
    - name: deps
      path: /public
  settings:
    hugo_version: 0.85.0
    validate: true
- name: deploy_dogeCloud
  image: git.frytea.local:80/songtianlun/upload-s3:latest
  pull: always
  volumes:
    - name: deps
      path: /public
  environment:
    S3_ENDPOINT:
      from_secret: S3_ENDPOINT
    S3_BUCKET:
      from_secret: S3_BUCKET
    S3_ACCESS_KEY_ID:
        from_secret: S3_AK
    S3_SECRET_ACCESS_KEY:
        from_secret: S3_SK
    GITEA_API_KEY:
        from_secret: gitea_api_key
  commands:
    - /uploader -V
    - /uploader
      -E $S3_ENDPOINT
      -B $S3_BUCKET
      -A $S3_ACCESS_KEY_ID
      -S $S3_SECRET_ACCESS_KEY
      -P './public'
      -T './'
#- name: deploy_Vercel
#  image: docker.io/kameshsampath/drone-vercel-deploy
#  pull: never
#  settings:
#    log_level: debug
#    # valid values are production, development, preview
#    vercel_env: production
#    vercel_token:
#      from_secret: vercel_token
#    vercel_org_id:
#      from_secret: vercel_org_id
#    vercel_project_id:
#      from_secret: vercel_project_id
#    vercel_project_create: true
#    vercel_environment:
#      - NEXT_PUBLIC_FOO=BAR
#      - NEXT_PUBLIC_XMAS=25 Dec
- name: deploy_vercel
  image: one000mph/drone-now        # Use one000mph's version as lucaperret's is outdated
  environment:
    NOW_TOKEN:
      from_secret: vercel_token
  settings:
    secret:           # Refers to the above environment variable
      from_secret: vercel_token
    deploy_name: songtianlun-github-io          # The name of your vercel project
    type: static
    team: songtianlun
    alias: www.frytea.com
#    prod: true                    # Leave this if you want to deploy to production, remove to disable production
    directory: public             # Only if you've pre-rendered the page. Normally you let vercel handle this
- name: notify
  image: drillster/drone-email
  settings:
    host:
      from_secret: SMTP_HOST
    port:
      from_secret: SMTP_PORT
    username:
      from_secret: SMTP_USERNAME
    password:
      from_secret: SMTP_PASSWORD
    from:
      from_secret: SMTP_USERNAME

volumes:
  - name: deps
    temp: {}

trigger:
  ref:
    - refs/tags/*
    - refs/heads/*