kind: pipeline
type: docker
name: default

clone:
  depth: 50
  tags: true
  skip_verify: true

steps:
- name: submodules
  image: alpine/git
  commands:
    - git submodule update --init --recursive
- name: build
  image: plugins/hugo
  volumes:
    - name: deps
      path: /public
  settings:
    hugo_version: 0.85.0
    validate: true
#- name: upload
#  image: golang
#  volumes:
#    - name: deps
#      path: /public
#  commands:
#    - go run main.go
- name: upload
  image: perl:5.30.3-bullseye
  volumes:
    - name: deps
      path: /public
  environment:
    S3_ENDPOINT:
      from_secret: S3_ENDPOINT
    S3_BUCKET:
      from_secret: S3_BUCKET
    S3_ACCESS_KEY_ID:
        from_secret: S3_AK
    S3_SECRET_ACCESS_KEY:
        from_secret: S3_SK
    GITEA_API_KEY:
        from_secret: gitea_api_key
  commands:
#    - apt-get update
#    - apt-get upgrade -y
#    - apt-get install -y libjson-perl
    - cpanm JSON
    - perl get-uploader.pl ${gitea_api_key}
    - chmod +x uploader
    - ./uploader -V
    - ./uploader \
      -E '$S3_ENDPOINT' \
      -B '$S3_BUCKET' \
      -A '$S3_ACCESS_KEY_ID' \
      -S '$S3_SECRET_ACCESS_KEY' \
      -P './public' \
      -T './'
- name: notify
  image: drillster/drone-email
  settings:
    host:
      from_secret: SMTP_HOST
    port:
      from_secret: SMTP_PORT
    username:
      from_secret: SMTP_USERNAME
    password:
      from_secret: SMTP_PASSWORD
    from:
      from_secret: SMTP_USERNAME

volumes:
  - name: deps
    temp: {}

trigger:
  ref:
    - refs/tags/*
    - refs/heads/*