kind: pipeline
type: docker
name: default

clone:
  depth: 50
  tags: true
  skip_verify: true

steps:
- name: submodules
  image: alpine/git
  commands:
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa git.frytea.local >> ~/.ssh/known_hosts
    - git submodule update --init --recursive
- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.85.0
    validate: true