kind: pipeline
type: docker
name: default

clone:
  depth: 50
  tags: true
  skip_verify: true

steps:
- name: submodules
  image: alpine/git
  commands:
    - git submodule update --init --recursive
- name: build
  image: plugins/hugo
  volumes:
    - name: deps
      path: /public
  settings:
    hugo_version: 0.85.0
    validate: true
#- name: upload
#  image: golang
#  volumes:
#    - name: deps
#      path: /public
#  commands:
#    - go run main.go
- name: upload
  image: 5.36-bullseye
  volumes:
    - name: deps
      path: /public
  environment:
    S3_ENDPOINT:
      from_secret: S3_ENDPOINT
    S3_BUCKET:
      from_secret: S3_BUCKET
    S3_ACCESS_KEY_ID:
        from_secret: S3_AK
    S3_SECRET_ACCESS_KEY:
        from_secret: S3_SK
  commands:
    - apt-get update
    - apt-get install -y libjson-perl
    - url=$(perl get-uploader-url.pl)
    - curl -k -L -o uploader $url
    - chmod +x uploader
    - ./uploader \
      -E '${S3_ENDPOINT}' \
      -B '${S3_BUCKET}' \
      -A '${S3_ACCESS_KEY_ID}' \
      -S '${9edec3898fc9d3d0fd9c6ea7e4e1c8bb}' \
      -P './public' \
      -T './'
- name: notify
  image: drillster/drone-email
  settings:
    host:
      from_secret: SMTP_HOST
    port:
      from_secret: SMTP_PORT
    username:
      from_secret: SMTP_USERNAME
    password:
      from_secret: SMTP_PASSWORD
    from:
      from_secret: SMTP_USERNAME

volumes:
  - name: deps
    temp: {}

trigger:
  ref:
    - refs/tags/*
    - refs/heads/*