kind: pipeline
type: docker
name: default

clone:
  depth: 50
  tags: true
  skip_verify: true

steps:
- name: submodules
  image: alpine/git
  commands:
    - git submodule update --init --recursive
- name: build
  image: plugins/hugo
  volumes:
    - name: deps
      path: /public
  settings:
    hugo_version: 0.85.0
    validate: true
- name: upload
  image: golang
  volumes:
    - name: deps
      path: /public
  commands:
    - go run main.go
- name: notify
  image: drillster/drone-email
  settings:
    host:
      from_secret: SMTP_HOST
    port: 465
    username: broadcast@frytea.com
    password:
      from_secret: SMTP_PASSWORD
    from: broadcast@frytea.com

volumes:
  - name: deps
    temp: {}

trigger:
  branch:
    - main
    - drone
  event:
    - push