name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      # 部署到阿里云 oss
      - name: Deploy to Aliyun OSS
        uses: manyuanrong/setup-ossutil@master
        with:
          endpoint: oss-cn-beijing.aliyuncs.com
          access-key-id: ${{ secrets.OSS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_KEY_SECRET }}
      - name: cp aliyun oss
        run: ossutil cp -rf public oss://frytea-homepage/

#      - name: Use Node.js
#        uses: actions/setup-node@v1
#        with:
#          node-version: '12.x'

      # - name: Push algolia search index
      #   run: |
      #     go mod tidy
      #     go run main.go
      #   env:
      #     ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      #     ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
      #     ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
      #     ALGOLIA_INDEX_FILE: "./public/index.json"

#      - name: Install CloudBase-Cli
#        run: npm install -g @cloudbase/cli
#
#      - name: Login to Tencent CloudBase
#        env:
#          SECRET_ID: ${{secrets.secretId}}
#          SECRET_KEY: ${{secrets.secretKey}}
#        run: tcb login --apiKeyId "$SECRET_ID" --apiKey "$SECRET_KEY"
#
#      - name: Deploy to Tencent CloudBase
#        env:
#          ENV_ID: ${{secrets.envId}}
#        run: tcb framework deploy -e "$ENV_ID"

      # 使用腾讯云云开发 Github Action 部署
      # - name: Deploy static to Tencent CloudBase
      #   id: deployStatic
      #   uses: TencentCloudBase/cloudbase-action@v2
      #   with:
      #     # 云开发的访问密钥 secretId 和 secretKey
      #     secretId: ${{ secrets.SECRET_ID }}
      #     secretKey: ${{ secrets.SECRET_KEY }}
      #     # 云开发的环境id
      #     envId: ${{ secrets.ENV_ID }}
      #     # Github 项目静态文件的路径
      #     # staticSrcPath: public

      # 用docker容器上传algolia索引文件
      # - uses: actions/checkout@v2
      #- name: Run container for atomic-algolia
      #  run: docker run --rm -e ALGOLIA_ADMIN_KEY=${{ secrets.ALGOLIA_ADMIN_KEY }} -e ALGOLIA_INDEX_FILE=/public/algolia.json -e ALGOLIA_APP_ID=${{ secrets.ALGOLIA_APP_ID }} -e ALGOLIA_INDEX_NAME=${{ secrets.ALGOLIA_INDEX_NAME }} -v $PWD/public:/public registry.cn-shenzhen.aliyuncs.com/lan-k8s/ubuntu:algolia atomic-algolia
