name: Test Sync (Debug)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Debug - Check environment
      run: |
        echo "=== DEBUG INFO ==="
        echo "Current directory: $(pwd)"
        echo "Current branch: $(git branch --show-current)"
        echo "Available branches:"
        git branch -a
        echo ""
        echo "Files in current directory:"
        ls -la
        echo ""
        echo "Git status:"
        git status
        
    - name: Try to find projects.json
      run: |
        echo "=== SEARCHING FOR projects.json ==="
        find . -name "projects.json" -type f
        echo ""
        if [ -f "projects.json" ]; then
          echo "✅ Found projects.json in current directory"
          head -5 projects.json
        else
          echo "❌ projects.json not found in current directory"
          echo "Checking project branch..."
          git checkout project || echo "Failed to checkout project branch"
          if [ -f "projects.json" ]; then
            echo "✅ Found projects.json in project branch"
            head -5 projects.json
          else
            echo "❌ projects.json not found in project branch either"
          fi
        fi
        
    - name: Test Node.js
      run: |
        echo "=== TESTING NODE.JS ==="
        node --version
        npm --version
        echo "Node.js test: $(node -e "console.log('Hello from Node.js')")"